/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CameraConfigSetResolution {
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
}

impl CameraConfigSetResolution {
    pub fn new() -> CameraConfigSetResolution {
        CameraConfigSetResolution {
            width: None,
            height: None,
        }
    }
}

