/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CameraConfigSet : Camera configuration to set
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CameraConfigSet {
    /// Name of the camera
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// When the snapshot is taken
    #[serde(rename = "trigger_scheme", skip_serializing_if = "Option::is_none")]
    pub trigger_scheme: Option<TriggerScheme>,
    #[serde(rename = "resolution", skip_serializing_if = "Option::is_none")]
    pub resolution: Option<Box<models::CameraConfigSetResolution>>,
    /// Current rotation of the output image
    #[serde(rename = "rotation", skip_serializing_if = "Option::is_none")]
    pub rotation: Option<i32>,
    /// Focus of the camera (0.0 - 1.0)
    #[serde(rename = "focus", skip_serializing_if = "Option::is_none")]
    pub focus: Option<f64>,
    #[serde(rename = "exposure", skip_serializing_if = "Option::is_none")]
    pub exposure: Option<f64>,
    #[serde(rename = "send_to_connect", skip_serializing_if = "Option::is_none")]
    pub send_to_connect: Option<bool>,
}

impl CameraConfigSet {
    /// Camera configuration to set
    pub fn new() -> CameraConfigSet {
        CameraConfigSet {
            name: None,
            trigger_scheme: None,
            resolution: None,
            rotation: None,
            focus: None,
            exposure: None,
            send_to_connect: None,
        }
    }
}
/// When the snapshot is taken
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TriggerScheme {
    #[serde(rename = "TEN_SEC")]
    TenSec,
    #[serde(rename = "THIRTY_SEC")]
    ThirtySec,
    #[serde(rename = "SIXTY_SEC")]
    SixtySec,
    #[serde(rename = "EACH_LAYER")]
    EachLayer,
    #[serde(rename = "FIFTH_LAYER")]
    FifthLayer,
    #[serde(rename = "MANUAL")]
    Manual,
}

impl Default for TriggerScheme {
    fn default() -> TriggerScheme {
        Self::TenSec
    }
}

