/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Camera {
    #[serde(rename = "camera_id", skip_serializing_if = "Option::is_none")]
    pub camera_id: Option<String>,
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Box<models::CameraConfig>>,
    /// Camera is successfully connected to PrusaLink
    #[serde(rename = "connected", skip_serializing_if = "Option::is_none")]
    pub connected: Option<bool>,
    /// Camera is detected by PrusaLink, but not saved yet
    #[serde(rename = "detected", skip_serializing_if = "Option::is_none")]
    pub detected: Option<bool>,
    /// Camera configuration is saved in PrusaLink
    #[serde(rename = "stored", skip_serializing_if = "Option::is_none")]
    pub stored: Option<bool>,
    /// Camera is linked to PrusaConnect
    #[serde(rename = "linked", skip_serializing_if = "Option::is_none")]
    pub linked: Option<bool>,
}

impl Camera {
    pub fn new() -> Camera {
        Camera {
            camera_id: None,
            config: None,
            connected: None,
            detected: None,
            stored: None,
            linked: None,
        }
    }
}

