/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    /// Prusa error code. Must be string if we will have printer with code for example 04
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Prusa error text string with prefilled variable macros.
    #[serde(rename = "title")]
    pub title: String,
    /// Prusa error text string with prefilled variable macros.
    #[serde(rename = "text")]
    pub text: String,
    /// Link to the Prusa help page
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl Error {
    pub fn new(title: String, text: String) -> Error {
        Error {
            code: None,
            title,
            text,
            url: None,
        }
    }
}

