/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FirmwareFileInfoAllOfMeta {
    /// Firmware version in text format
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "printer_type", skip_serializing_if = "Option::is_none")]
    pub printer_type: Option<i32>,
    #[serde(rename = "printer_version", skip_serializing_if = "Option::is_none")]
    pub printer_version: Option<i32>,
}

impl FirmwareFileInfoAllOfMeta {
    pub fn new() -> FirmwareFileInfoAllOfMeta {
        FirmwareFileInfoAllOfMeta {
            version: None,
            printer_type: None,
            printer_version: None,
        }
    }
}

