/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FolderInfoAllOfChildren {
    FileInfo(Box<models::FileInfo>),
    PrintFileInfoBasic(Box<models::PrintFileInfoBasic>),
    FirmwareFileInfoBasic(Box<models::FirmwareFileInfoBasic>),
    FolderInfo(Box<models::FolderInfo>),
}

impl Default for FolderInfoAllOfChildren {
    fn default() -> Self {
        Self::FileInfo(Default::default())
    }
}
/// File could be print file, firmware file, other (e.g. configuration) file, or folder
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "PRINT_FILE")]
    PrintFile,
    #[serde(rename = "FIRMWARE")]
    Firmware,
    #[serde(rename = "FILE")]
    File,
    #[serde(rename = "FOLDER")]
    Folder,
}

impl Default for Type {
    fn default() -> Type {
        Self::PrintFile
    }
}

