/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GenericFileInfo : Basic file info object, common for all files
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenericFileInfo {
    /// Short Filename
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "read_only")]
    pub read_only: bool,
    /// Available for files only, not for folders
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    /// File could be print file, firmware file, other (e.g. configuration) file, or folder
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Timestamp in seconds
    #[serde(rename = "m_timestamp")]
    pub m_timestamp: i32,
    /// Long Filename
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}

impl GenericFileInfo {
    /// Basic file info object, common for all files
    pub fn new(name: String, read_only: bool, r#type: Type, m_timestamp: i32) -> GenericFileInfo {
        GenericFileInfo {
            name,
            read_only,
            size: None,
            r#type,
            m_timestamp,
            display_name: None,
        }
    }
}
/// File could be print file, firmware file, other (e.g. configuration) file, or folder
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "PRINT_FILE")]
    PrintFile,
    #[serde(rename = "FIRMWARE")]
    Firmware,
    #[serde(rename = "FILE")]
    File,
    #[serde(rename = "FOLDER")]
    Folder,
}

impl Default for Type {
    fn default() -> Type {
        Self::PrintFile
    }
}

