/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPrinterStatus200Response {
    #[serde(rename = "job", skip_serializing_if = "Option::is_none")]
    pub job: Option<Box<models::StatusJob>>,
    #[serde(rename = "printer")]
    pub printer: Box<models::StatusPrinter>,
    #[serde(rename = "transfer", skip_serializing_if = "Option::is_none")]
    pub transfer: Option<Box<models::StatusTransfer>>,
    #[serde(rename = "storage", skip_serializing_if = "Option::is_none")]
    pub storage: Option<Box<models::StatusStorage>>,
    #[serde(rename = "camera", skip_serializing_if = "Option::is_none")]
    pub camera: Option<Box<models::StatusCamera>>,
}

impl GetPrinterStatus200Response {
    pub fn new(printer: models::StatusPrinter) -> GetPrinterStatus200Response {
        GetPrinterStatus200Response {
            job: None,
            printer: Box::new(printer),
            transfer: None,
            storage: None,
            camera: None,
        }
    }
}

