/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStorage200Response {
    #[serde(rename = "storage_list", skip_serializing_if = "Option::is_none")]
    pub storage_list: Option<Vec<models::Storage>>,
}

impl GetStorage200Response {
    pub fn new() -> GetStorage200Response {
        GetStorage200Response {
            storage_list: None,
        }
    }
}

