/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Info {
    #[serde(rename = "mmu", skip_serializing_if = "Option::is_none")]
    pub mmu: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(rename = "farm_mode", skip_serializing_if = "Option::is_none")]
    pub farm_mode: Option<bool>,
    #[serde(rename = "nozzle_diameter", skip_serializing_if = "Option::is_none")]
    pub nozzle_diameter: Option<f64>,
    #[serde(rename = "min_extrusion_temp", skip_serializing_if = "Option::is_none")]
    pub min_extrusion_temp: Option<i32>,
    #[serde(rename = "serial", skip_serializing_if = "Option::is_none")]
    pub serial: Option<String>,
    #[serde(rename = "sd_ready", skip_serializing_if = "Option::is_none")]
    pub sd_ready: Option<bool>,
    #[serde(rename = "active_camera", skip_serializing_if = "Option::is_none")]
    pub active_camera: Option<bool>,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<String>,
    #[serde(rename = "network_error_chime", skip_serializing_if = "Option::is_none")]
    pub network_error_chime: Option<bool>,
}

impl Info {
    pub fn new() -> Info {
        Info {
            mmu: None,
            name: None,
            location: None,
            farm_mode: None,
            nozzle_diameter: None,
            min_extrusion_temp: None,
            serial: None,
            sd_ready: None,
            active_camera: None,
            hostname: None,
            port: None,
            network_error_chime: None,
        }
    }
}

