/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Job {
    /// Whether the printer is printing from the serial line
    #[serde(rename = "serial_print", skip_serializing_if = "Option::is_none")]
    pub serial_print: Option<bool>,
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<Box<models::JobFilePrintFile>>,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "state")]
    pub state: State,
    /// Percents
    #[serde(rename = "progress")]
    pub progress: f64,
    /// Seconds
    #[serde(rename = "time_remaining", skip_serializing_if = "Option::is_none")]
    pub time_remaining: Option<i32>,
    /// Seconds
    #[serde(rename = "time_printing")]
    pub time_printing: i32,
    /// Whether the time estimates are accurate or inaccurate
    #[serde(rename = "inaccurate_estimates", skip_serializing_if = "Option::is_none")]
    pub inaccurate_estimates: Option<bool>,
}

impl Job {
    pub fn new(id: i32, state: State, progress: f64, time_printing: i32) -> Job {
        Job {
            serial_print: None,
            file: None,
            id,
            state,
            progress,
            time_remaining: None,
            time_printing,
            inaccurate_estimates: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "PRINTING")]
    Printing,
    #[serde(rename = "PAUSED")]
    Paused,
    #[serde(rename = "FINISHED")]
    Finished,
    #[serde(rename = "STOPPED")]
    Stopped,
    #[serde(rename = "ERROR")]
    Error,
}

impl Default for State {
    fn default() -> State {
        Self::Printing
    }
}

