/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobFilePrintFile {
    /// Short Filename
    #[serde(rename = "name")]
    pub name: String,
    /// Long Filename
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "display_path", skip_serializing_if = "Option::is_none")]
    pub display_path: Option<String>,
    /// Bytes
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    /// Timestamp in seconds
    #[serde(rename = "m_timestamp")]
    pub m_timestamp: i32,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::PrintFileMetadata>>,
    #[serde(rename = "refs", skip_serializing_if = "Option::is_none")]
    pub refs: Option<Box<models::PrintFileRefs>>,
}

impl JobFilePrintFile {
    pub fn new(name: String, path: String, m_timestamp: i32) -> JobFilePrintFile {
        JobFilePrintFile {
            name,
            display_name: None,
            path,
            display_path: None,
            size: None,
            m_timestamp,
            meta: None,
            refs: None,
        }
    }
}

