/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobFilePrint {
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<Box<models::JobFilePrintFile>>,
}

impl JobFilePrint {
    pub fn new() -> JobFilePrint {
        JobFilePrint {
            file: None,
        }
    }
}

