/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobSerialPrint {
    /// Whether the printer is printing from the serial line
    #[serde(rename = "serial_print", skip_serializing_if = "Option::is_none")]
    pub serial_print: Option<bool>,
}

impl JobSerialPrint {
    pub fn new() -> JobSerialPrint {
        JobSerialPrint {
            serial_print: None,
        }
    }
}

