/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrintFileRefs : Reference links for file thumbnail, icon and download
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrintFileRefs {
    #[serde(rename = "download", skip_serializing_if = "Option::is_none")]
    pub download: Option<String>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "thumbnail", skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<String>,
}

impl PrintFileRefs {
    /// Reference links for file thumbnail, icon and download
    pub fn new() -> PrintFileRefs {
        PrintFileRefs {
            download: None,
            icon: None,
            thumbnail: None,
        }
    }
}

