/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrintFileMetadata : Print file metadata parsed from G-code or SL1, all data are optional
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrintFileMetadata {
    /// Degrees Celsius
    #[serde(rename = "bed_temperature", skip_serializing_if = "Option::is_none")]
    pub bed_temperature: Option<i32>,
    #[serde(rename = "bed_temperature per tool", skip_serializing_if = "Option::is_none")]
    pub bed_temperature_per_tool: Option<Vec<i32>>,
    /// Nozzle temperature, Degrees Celsius
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<i32>,
    #[serde(rename = "temperature per tool", skip_serializing_if = "Option::is_none")]
    pub temperature_per_tool: Option<Vec<i32>>,
    /// Millimeters
    #[serde(rename = "brim_width", skip_serializing_if = "Option::is_none")]
    pub brim_width: Option<i32>,
    #[serde(rename = "estimated printing time (normal mode)", skip_serializing_if = "Option::is_none")]
    pub estimated_printing_time_left_parenthesis_normal_mode_right_parenthesis: Option<String>,
    /// Seconds
    #[serde(rename = "estimated_print_time", skip_serializing_if = "Option::is_none")]
    pub estimated_print_time: Option<i32>,
    #[serde(rename = "faded_layers", skip_serializing_if = "Option::is_none")]
    pub faded_layers: Option<i32>,
    #[serde(rename = "filament cost", skip_serializing_if = "Option::is_none")]
    pub filament_cost: Option<f64>,
    #[serde(rename = "filament cost per tool", skip_serializing_if = "Option::is_none")]
    pub filament_cost_per_tool: Option<Vec<f64>>,
    #[serde(rename = "filament used [cm3]", skip_serializing_if = "Option::is_none")]
    pub filament_used_left_square_bracket_cm3_right_square_bracket: Option<f64>,
    #[serde(rename = "filament used [cm3] per tool", skip_serializing_if = "Option::is_none")]
    pub filament_used_left_square_bracket_cm3_right_square_bracket__per_tool: Option<Vec<f64>>,
    #[serde(rename = "filament used [g]", skip_serializing_if = "Option::is_none")]
    pub filament_used_left_square_bracket_g_right_square_bracket: Option<f64>,
    #[serde(rename = "filament used [g] per tool", skip_serializing_if = "Option::is_none")]
    pub filament_used_left_square_bracket_g_right_square_bracket__per_tool: Option<Vec<f64>>,
    #[serde(rename = "filament used [mm]", skip_serializing_if = "Option::is_none")]
    pub filament_used_left_square_bracket_mm_right_square_bracket: Option<f64>,
    #[serde(rename = "filament used [mm] per tool", skip_serializing_if = "Option::is_none")]
    pub filament_used_left_square_bracket_mm_right_square_bracket__per_tool: Option<Vec<f64>>,
    #[serde(rename = "filament_type", skip_serializing_if = "Option::is_none")]
    pub filament_type: Option<String>,
    #[serde(rename = "filament_type per tool", skip_serializing_if = "Option::is_none")]
    pub filament_type_per_tool: Option<Vec<String>>,
    /// Percents
    #[serde(rename = "fill_density", skip_serializing_if = "Option::is_none")]
    pub fill_density: Option<String>,
    /// Seconds
    #[serde(rename = "initial_exposure_time", skip_serializing_if = "Option::is_none")]
    pub initial_exposure_time: Option<i32>,
    /// Millimeters
    #[serde(rename = "layer_height", skip_serializing_if = "Option::is_none")]
    pub layer_height: Option<f64>,
    #[serde(rename = "material_name", skip_serializing_if = "Option::is_none")]
    pub material_name: Option<String>,
    /// Seconds
    #[serde(rename = "exposure_time", skip_serializing_if = "Option::is_none")]
    pub exposure_time: Option<i32>,
    /// Seconds
    #[serde(rename = "max_exposure_time", skip_serializing_if = "Option::is_none")]
    pub max_exposure_time: Option<i32>,
    /// Seconds
    #[serde(rename = "max_initial_exposure_time", skip_serializing_if = "Option::is_none")]
    pub max_initial_exposure_time: Option<i32>,
    /// Seconds
    #[serde(rename = "min_exposure_time", skip_serializing_if = "Option::is_none")]
    pub min_exposure_time: Option<i32>,
    /// Seconds
    #[serde(rename = "min_initial_exposure_time", skip_serializing_if = "Option::is_none")]
    pub min_initial_exposure_time: Option<i32>,
    /// Millimeters
    #[serde(rename = "nozzle_diameter", skip_serializing_if = "Option::is_none")]
    pub nozzle_diameter: Option<f64>,
    #[serde(rename = "nozzle_diameter per tool", skip_serializing_if = "Option::is_none")]
    pub nozzle_diameter_per_tool: Option<Vec<f64>>,
    #[serde(rename = "normal_percent_present", skip_serializing_if = "Option::is_none")]
    pub normal_percent_present: Option<bool>,
    #[serde(rename = "normal_left_present", skip_serializing_if = "Option::is_none")]
    pub normal_left_present: Option<bool>,
    #[serde(rename = "quiet_percent_present", skip_serializing_if = "Option::is_none")]
    pub quiet_percent_present: Option<bool>,
    #[serde(rename = "quiet_left_present", skip_serializing_if = "Option::is_none")]
    pub quiet_left_present: Option<bool>,
    #[serde(rename = "layer_info_present", skip_serializing_if = "Option::is_none")]
    pub layer_info_present: Option<bool>,
    #[serde(rename = "max_layer_z", skip_serializing_if = "Option::is_none")]
    pub max_layer_z: Option<f64>,
    /// Seconds
    #[serde(rename = "print_time", skip_serializing_if = "Option::is_none")]
    pub print_time: Option<i32>,
    #[serde(rename = "printer_model", skip_serializing_if = "Option::is_none")]
    pub printer_model: Option<PrinterModel>,
    #[serde(rename = "support_material", skip_serializing_if = "Option::is_none")]
    pub support_material: Option<String>,
    #[serde(rename = "ironing", skip_serializing_if = "Option::is_none")]
    pub ironing: Option<i32>,
    #[serde(rename = "required_resin_ml", skip_serializing_if = "Option::is_none")]
    pub required_resin_ml: Option<f64>,
    #[serde(rename = "profile", skip_serializing_if = "Option::is_none")]
    pub profile: Option<String>,
}

impl PrintFileMetadata {
    /// Print file metadata parsed from G-code or SL1, all data are optional
    pub fn new() -> PrintFileMetadata {
        PrintFileMetadata {
            bed_temperature: None,
            bed_temperature_per_tool: None,
            temperature: None,
            temperature_per_tool: None,
            brim_width: None,
            estimated_printing_time_left_parenthesis_normal_mode_right_parenthesis: None,
            estimated_print_time: None,
            faded_layers: None,
            filament_cost: None,
            filament_cost_per_tool: None,
            filament_used_left_square_bracket_cm3_right_square_bracket: None,
            filament_used_left_square_bracket_cm3_right_square_bracket__per_tool: None,
            filament_used_left_square_bracket_g_right_square_bracket: None,
            filament_used_left_square_bracket_g_right_square_bracket__per_tool: None,
            filament_used_left_square_bracket_mm_right_square_bracket: None,
            filament_used_left_square_bracket_mm_right_square_bracket__per_tool: None,
            filament_type: None,
            filament_type_per_tool: None,
            fill_density: None,
            initial_exposure_time: None,
            layer_height: None,
            material_name: None,
            exposure_time: None,
            max_exposure_time: None,
            max_initial_exposure_time: None,
            min_exposure_time: None,
            min_initial_exposure_time: None,
            nozzle_diameter: None,
            nozzle_diameter_per_tool: None,
            normal_percent_present: None,
            normal_left_present: None,
            quiet_percent_present: None,
            quiet_left_present: None,
            layer_info_present: None,
            max_layer_z: None,
            print_time: None,
            printer_model: None,
            support_material: None,
            ironing: None,
            required_resin_ml: None,
            profile: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrinterModel {
    #[serde(rename = "MK3")]
    Mk3,
    #[serde(rename = "MK3S")]
    Mk3S,
    #[serde(rename = "MINI")]
    Mini,
}

impl Default for PrinterModel {
    fn default() -> PrinterModel {
        Self::Mk3
    }
}

