/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrusaLinkPackage : PrusaLink package version available to update
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrusaLinkPackage {
    /// Package version available for update
    #[serde(rename = "new_version", skip_serializing_if = "Option::is_none")]
    pub new_version: Option<String>,
}

impl PrusaLinkPackage {
    /// PrusaLink package version available to update
    pub fn new() -> PrusaLinkPackage {
        PrusaLinkPackage {
            new_version: None,
        }
    }
}

