/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusStorage : Telemetry info about current storage status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusStorage {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "read_only")]
    pub read_only: bool,
    #[serde(rename = "free_space", skip_serializing_if = "Option::is_none")]
    pub free_space: Option<i32>,
}

impl StatusStorage {
    /// Telemetry info about current storage status
    pub fn new(name: String, path: String, read_only: bool) -> StatusStorage {
        StatusStorage {
            name,
            path,
            read_only,
            free_space: None,
        }
    }
}

