/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusPrinter : Telemetry info about printer, all values except state are optional
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusPrinter {
    #[serde(rename = "state")]
    pub state: State,
    #[serde(rename = "temp_nozzle", skip_serializing_if = "Option::is_none")]
    pub temp_nozzle: Option<f64>,
    #[serde(rename = "target_nozzle", skip_serializing_if = "Option::is_none")]
    pub target_nozzle: Option<f64>,
    #[serde(rename = "temp_bed", skip_serializing_if = "Option::is_none")]
    pub temp_bed: Option<f64>,
    #[serde(rename = "target_bed", skip_serializing_if = "Option::is_none")]
    pub target_bed: Option<f64>,
    /// Available only when printer is not moving
    #[serde(rename = "axis_x", skip_serializing_if = "Option::is_none")]
    pub axis_x: Option<f64>,
    /// Available only when printer is not moving
    #[serde(rename = "axis_y", skip_serializing_if = "Option::is_none")]
    pub axis_y: Option<f64>,
    #[serde(rename = "axis_z", skip_serializing_if = "Option::is_none")]
    pub axis_z: Option<f64>,
    #[serde(rename = "flow", skip_serializing_if = "Option::is_none")]
    pub flow: Option<i32>,
    #[serde(rename = "speed", skip_serializing_if = "Option::is_none")]
    pub speed: Option<i32>,
    #[serde(rename = "fan_hotend", skip_serializing_if = "Option::is_none")]
    pub fan_hotend: Option<i32>,
    #[serde(rename = "fan_print", skip_serializing_if = "Option::is_none")]
    pub fan_print: Option<i32>,
    #[serde(rename = "status_printer", skip_serializing_if = "Option::is_none")]
    pub status_printer: Option<Box<models::StatusPrinterStatusPrinter>>,
    #[serde(rename = "status_connect", skip_serializing_if = "Option::is_none")]
    pub status_connect: Option<Box<models::StatusPrinterStatusPrinter>>,
}

impl StatusPrinter {
    /// Telemetry info about printer, all values except state are optional
    pub fn new(state: State) -> StatusPrinter {
        StatusPrinter {
            state,
            temp_nozzle: None,
            target_nozzle: None,
            temp_bed: None,
            target_bed: None,
            axis_x: None,
            axis_y: None,
            axis_z: None,
            flow: None,
            speed: None,
            fan_hotend: None,
            fan_print: None,
            status_printer: None,
            status_connect: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "IDLE")]
    Idle,
    #[serde(rename = "BUSY")]
    Busy,
    #[serde(rename = "PRINTING")]
    Printing,
    #[serde(rename = "PAUSED")]
    Paused,
    #[serde(rename = "FINISHED")]
    Finished,
    #[serde(rename = "STOPPED")]
    Stopped,
    #[serde(rename = "ERROR")]
    Error,
    #[serde(rename = "ATTENTION")]
    Attention,
    #[serde(rename = "READY")]
    Ready,
}

impl Default for State {
    fn default() -> State {
        Self::Idle
    }
}

