/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusTransfer : Telemetry info about current transfer status, all values except id and time_transferring are optional
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusTransfer {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "time_transferring")]
    pub time_transferring: i32,
    /// Percents
    #[serde(rename = "progress", skip_serializing_if = "Option::is_none")]
    pub progress: Option<f64>,
    #[serde(rename = "data_transferred", skip_serializing_if = "Option::is_none")]
    pub data_transferred: Option<i32>,
}

impl StatusTransfer {
    /// Telemetry info about current transfer status, all values except id and time_transferring are optional
    pub fn new(id: i32, time_transferring: i32) -> StatusTransfer {
        StatusTransfer {
            id,
            time_transferring,
            progress: None,
            data_transferred: None,
        }
    }
}

