/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusCamera : Telemetry info about default working camera, if available
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusCamera {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl StatusCamera {
    /// Telemetry info about default working camera, if available
    pub fn new() -> StatusCamera {
        StatusCamera {
            id: None,
        }
    }
}

