/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusJob : Telemetry info about current job, all values are optional
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusJob {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Percents
    #[serde(rename = "progress", skip_serializing_if = "Option::is_none")]
    pub progress: Option<f64>,
    /// Seconds
    #[serde(rename = "time_remaining", skip_serializing_if = "Option::is_none")]
    pub time_remaining: Option<i32>,
    /// Seconds
    #[serde(rename = "time_printing", skip_serializing_if = "Option::is_none")]
    pub time_printing: Option<i32>,
}

impl StatusJob {
    /// Telemetry info about current job, all values are optional
    pub fn new() -> StatusJob {
        StatusJob {
            id: None,
            progress: None,
            time_remaining: None,
            time_printing: None,
        }
    }
}

