/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Storage {
    /// Name of the storage, based on selected language
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Storage source
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Path to storage (not display path)
    #[serde(rename = "path")]
    pub path: String,
    /// Size of all print files in bytes
    #[serde(rename = "print_files", skip_serializing_if = "Option::is_none")]
    pub print_files: Option<i32>,
    /// Size of all system files in bytes
    #[serde(rename = "system_files", skip_serializing_if = "Option::is_none")]
    pub system_files: Option<i32>,
    /// System free space in bytes
    #[serde(rename = "free_space", skip_serializing_if = "Option::is_none")]
    pub free_space: Option<i32>,
    /// System total space in bytes
    #[serde(rename = "total_space", skip_serializing_if = "Option::is_none")]
    pub total_space: Option<i32>,
    /// Whether the storage is available or not
    #[serde(rename = "available")]
    pub available: bool,
    /// Whether the storage is read only
    #[serde(rename = "read_only", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
}

impl Storage {
    pub fn new(r#type: Type, path: String, available: bool) -> Storage {
        Storage {
            name: None,
            r#type,
            path,
            print_files: None,
            system_files: None,
            free_space: None,
            total_space: None,
            available,
            read_only: None,
        }
    }
}
/// Storage source
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "LOCAL")]
    Local,
    #[serde(rename = "SDCARD")]
    Sdcard,
    #[serde(rename = "USB")]
    Usb,
}

impl Default for Type {
    fn default() -> Type {
        Self::Local
    }
}

