/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transfer {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Long Filename
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Bytes
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<String>,
    /// Percents
    #[serde(rename = "progress")]
    pub progress: f64,
    /// Transferred data in bytes
    #[serde(rename = "transferred")]
    pub transferred: i32,
    /// Seconds
    #[serde(rename = "time_remaining", skip_serializing_if = "Option::is_none")]
    pub time_remaining: Option<i32>,
    /// Seconds
    #[serde(rename = "time_transferring")]
    pub time_transferring: i32,
    /// Whether or not print after finishing transfer (upload)
    #[serde(rename = "to_print")]
    pub to_print: bool,
}

impl Transfer {
    pub fn new(r#type: Type, display_name: String, path: String, progress: f64, transferred: i32, time_transferring: i32, to_print: bool) -> Transfer {
        Transfer {
            r#type,
            display_name,
            path,
            url: None,
            size: None,
            progress,
            transferred,
            time_remaining: None,
            time_transferring,
            to_print,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "NO_TRANSFER")]
    NoTransfer,
    #[serde(rename = "FROM_WEB")]
    FromWeb,
    #[serde(rename = "FROM_CONNECT")]
    FromConnect,
    #[serde(rename = "FROM_PRINTER")]
    FromPrinter,
    #[serde(rename = "FROM_SLICER")]
    FromSlicer,
    #[serde(rename = "FROM_CLIENT")]
    FromClient,
    #[serde(rename = "TO_CONNECT")]
    ToConnect,
    #[serde(rename = "TO_CLIENT")]
    ToClient,
}

impl Default for Type {
    fn default() -> Type {
        Self::NoTransfer
    }
}

