/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VersionCapabilities : Additional capabilities the printer has. The object is expected to be extended in the future with more capabilities. The absence of a capability in the object, or the complete absence of the object means the printer doesn't support such capability (probably doesn't even know such capability might exist). 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionCapabilities {
    /// The printer supports uploading GCodes by the PUT method (as described in this document). It is capable of doing the PUT and HEAD to /api/v1/files/{storage}/{path} and it is capable of answering the /api/v1/storage endpoint.  In absence of this capability, client MAY opt to try the legacy \"octoprint\" POST to /api/files/{storage}. 
    #[serde(rename = "upload-by-put", skip_serializing_if = "Option::is_none")]
    pub upload_by_put: Option<bool>,
}

impl VersionCapabilities {
    /// Additional capabilities the printer has. The object is expected to be extended in the future with more capabilities. The absence of a capability in the object, or the complete absence of the object means the printer doesn't support such capability (probably doesn't even know such capability might exist). 
    pub fn new() -> VersionCapabilities {
        VersionCapabilities {
            upload_by_put: None,
        }
    }
}

