/*
 * PrusaLink Web
 *
 * This is a printer webservice.  This OpenAPI document is normalized for Progenitor/Rust client generation.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * Contact: link@prusa3d.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Version {
    #[serde(rename = "api")]
    pub api: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "printer")]
    pub printer: String,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "firmware")]
    pub firmware: String,
    #[serde(rename = "sdk", skip_serializing_if = "Option::is_none")]
    pub sdk: Option<String>,
    #[serde(rename = "capabilities", skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<Box<models::VersionCapabilities>>,
}

impl Version {
    pub fn new(api: String, version: String, printer: String, text: String, firmware: String) -> Version {
        Version {
            api,
            version,
            printer,
            text,
            firmware,
            sdk: None,
            capabilities: None,
        }
    }
}

